EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "Benchmark"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
TEST_SIZE: 0.25
WINDOW_LENGTH: 125
MODEL_A: "eegnetv4"
MODEL_B: "eegnetv1"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: False
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 2
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit;Delta;SS;IMD;MERLIN"
  MAX_DEPTH: 6