EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "Benchmark"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
WINDOW_LENGTH: 125
MODEL_A: "eegnetv1"
MODEL_B: "eegnetv4"
AUGMENTATION: "NONE"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: True
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit;Delta_Official;SS;IMD;MERLIN"
  MAX_DEPTH: 6