EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "Delta"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "eegnetv1"
MODEL_B: "eegnetv4"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    THRESHOLD: 8.0
EXPLAINER:
  TYPE: "Delta"
  MAX_DEPTH: 4