EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "IMD"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "eegnetv1"
MODEL_B: "eegnetv4"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "IMD"
  MAX_DEPTH: 6