EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "Logit"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "eegnetv1"
MODEL_B: "eegnetv4"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Logit"