EXPERIMENT:
  PROJECT: "BCIIV2a"
  TAG: "MERLIN"
DATASET: "BCIIV2a"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "eegnetv1"
MODEL_B: "eegnetv4"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: False
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "MERLIN"
  MAX_DEPTH: 6