EXPERIMENT:
  PROJECT: "Consensus"
  TAG: "CamCAN"
DATASET: "CamCAN"
NUM_SAMPLES: 2000
MODELS: ["linear", "mlp", "hgrn", "lfcnn", "varcnn", "ctnet"]  # 总计需要11s
EXPLAINER:
  TYPE: "ShapleyValueExplainer"
  W: 1
  M: 64
  RANGE_REFERENCES: -1000
