EXPERIMENT:
  PROJECT: "Consensus"
  TAG: "CamCAN"
DATASET: "CamCAN"
MODELS: ["mlp", "lfcnn", "varcnn", "hgrn", "linear"]  # "atcnet", "sdt"处理速度过慢，可能需要修改实现
EXPLAINER:
  TYPE: "ShapleyValueExplainer"
  W: 1
  M: 64
