EXPERIMENT:
  PROJECT: "Consensus"
  TAG: "CamCAN"
DATASET: "CamCAN"
NUM_SAMPLES: 2000
MODELS: ["ctnet"]  # eegnex平均时间：2min；ctnet：30s；msvtnet：1min
EXPLAINER:
  TYPE: "ShapleyValueExplainer"
  W: 1
  M: 64
  RANGE_REFERENCES: -1000
