EXPERIMENT:
  PROJECT: "Consensus"
  TAG: "CamCAN"
DATASET: "CamCAN"
NUM_SAMPLES: 2000 # w5完成了2000，w1完成了160
MODELS: ["ctnet"]  # "atcnet"处理速度过慢，可能需要修改实现
EXPLAINER:
  TYPE: "ShapleyValueExplainer"
  W: 1
  M: 8
  RANGE_REFERENCES: -1000
