EXPERIMENT:
  PROJECT: "Consensus"
  TAG: "DecMeg2014"
DATASET: "DecMeg2014"
MODELS: ["linear", "mlp", "hgrn", "lfcnn", "varcnn"]  # "atcnet"处理速度过慢，可能需要修改实现
EXPLAINER:
  TYPE: "ShapleyValueExplainer"
  W: 5
  M: 64
