EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Ablation"
DATASET: "CamCAN"
NUM_SPLITS: 5
TEST_SIZE: 0.25
WINDOW_LENGTH: 10
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: False
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 2
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit;Delta;SS;IMD" # "Logit;Delta;SS;IMD"
  MAX_DEPTH: 6