EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Delta"
DATASET: "CamCAN"
NUM_SPLITS: 3
WINDOW_LENGTH: 5
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Delta"