EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "IMD"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: False
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 2
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "IMD"