EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "IMD,Sel"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "IMD"