EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "linear"
MODEL_B: "varcnn"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 16
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6