EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit,Aug,Sel"
  CPU_COUNT: 8
DATASET: "CamCAN"
NUM_SPLITS: 3
WINDOW_LENGTH: 5
MODEL_A: "varcnn"
MODEL_B: "hgrn"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "Logit"