EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "rf"
MODEL_B: "varcnn"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: 3.0
Feature_SMOOTHING: False
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 4
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6