EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit,Aug,Sel"
  CPU_COUNT: 8
DATASET: "CamCAN"
NUM_SPLITS: 3
WINDOW_LENGTH: 5
MODEL_A: "mlp"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
EXTRACTION: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.01
EXPLAINER:
  TYPE: "Logit"