EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit,Aug,Sel"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "hgrn"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "Logit"