EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "mlp"
MODEL_B: "varcnn"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6