EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit,Aug"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Logit"