EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Logit"
DATASET: "CamCAN"
NUM_SPLITS: 3
WINDOW_LENGTH: 5
MODEL_A: "varcnn"
MODEL_B: "hgrn"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Logit"