EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "MERLIN"
DATASET: "CamCAN"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "MERLIN"