EXPERIMENT:
  PROJECT: "CamCAN"
  TAG: "Search"
DATASET: "CamCAN"
NUM_SPLITS: 5
TEST_SIZE: 0.25
WINDOW_LENGTH: 10
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: [0, 1.0, 3.0, 5.0]
Feature_SMOOTHING: False  # 平滑无优势
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 2
    THRESHOLD: [1.0, 3.0, 5.0]
EXPLAINER:
  TYPE: "SS;IMD" # "Logit;Delta;SS;IMD"
  MAX_DEPTH: [4, 5, 6, 7]