EXPERIMENT:
  NAME: ""
  TAG: "sdt_hgrn_fakd, sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_sdt_hgrn_fakd"
  B: "DecMeg2014_sdt"
AUGMENTATION:
  TYPE: "NONE"
NORMALIZATION:
  FLAG: True
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.05
  Diff:
    WINDOW_LENGTH: 25
    M: 16
EXPLAINER:
  TYPE: "Delta"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 2