EXPERIMENT:
  NAME: ""
  TAG: "sdt_hgrn_fakd, hgrn"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_sdt_hgrn_fakd"
  B: "DecMeg2014_hgrn"
AUGMENTATION:
  TYPE: "BASE"
NORMALIZATION:
  FLAG: True
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "NONE"
  RATE: 0.05
  Diff:
    WINDOW_LENGTH: 25
    M: 4
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 5
  MIN_SAMPLES_LEAF: 2