DATASET: "DecMeg2014"
NUM_SPLITS: 3
WINDOW_LENGTH: 10
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "BASE"
NORMALIZATION: True
EXTRACTION: True
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.1
  Diff:
    M: 8
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 1