EXPERIMENT:
  DATASET: "DecMeg2014"
  MODEL_A: "sdt_hgrn_fakd"
  MODEL_B: "sdt"
  NUM_SPLITS: 3
AUGMENTATION:
  TYPE: "BASE"
NORMALIZATION:
  FLAG: False
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.1
  Diff:
    WINDOW_LENGTH: 10
    M: 8
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 2