EXPERIMENT:
  NAME: ""
  TAG: "sdt_varcnn_kd, sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "CamCAN_sdt_varcnn_kd"
  B: "CamCAN_sdt"
EXPLAINER:
  TYPE: "LogitDeltaRule"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 4