EXPERIMENT:
  NAME: ""
  TAG: "sdt_hgrn_kd, sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
MODELS:
  A: "DecMeg2014_sdt_hgrn_kd"
  B: "DecMeg2014_sdt"
GLOBAL:
LOCAL:
