EXPERIMENT:
  NAME: ""
  TAG: "varcnn,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  NUM_SPLITS: 5
MODELS:
  A: "CamCAN_varcnn"
  B: "CamCAN_sdt" #"CamCAN_sdt_varcnn_fakd"
EXPLAINER:
  TYPE: "LogitDeltaRule"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 4