EXPERIMENT:
  NAME: ""
  TAG: "varcnn,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "CamCAN_varcnn"
  B: "CamCAN_sdt" #"CamCAN_sdt_varcnn_fakd"
AUGMENTATION:
  TYPE: "NONE"
NORMALIZATION:
  FLAG: True
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.0625
  Diff:
    WINDOW_LENGTH: 25
    M: 4
EXPLAINER:
  TYPE: "Delta"
  MAX_DEPTH: 5
  MIN_SAMPLES_LEAF: 2