EXPERIMENT:
  NAME: ""
  TAG: "varcnn,sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  NUM_SPLITS: 5
MODELS:
  A: "CamCAN_varcnn"
  B: "CamCAN_sdt" #"CamCAN_sdt_varcnn_fakd"
AUGMENTATION:
  TYPE: "BASE"
NORMALIZATION:
  FLAG: False
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "NONE"
  RATE: 0.0625
  Diff:
    WINDOW_LENGTH: 50
    M: 2
EXPLAINER:
  TYPE: "Logit"
#  MAX_DEPTH: 4
#  MIN_SAMPLES_LEAF: 1