EXPERIMENT:
  NAME: ""
  TAG: "varcnn,hgrn"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "CamCAN_varcnn"
  B: "CamCAN_hgrn"
AUGMENTATION:
  TYPE: "NONE"
SELECTION:
  TYPE: "NONE"
  RATE: 0.01
EXPLAINER:
  TYPE: "Delta"
  MAX_DEPTH: 5
  MIN_SAMPLES_LEAF: 2