EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Ablation"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
TEST_SIZE: 0.25
WINDOW_LENGTH: 25  # 25 10 5 1  10最好
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: [0, 3.0]
Feature_SMOOTHING: False  # 平滑无优势
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 2
    THRESHOLD: [0, 3.0]
EXPLAINER:
  TYPE: "Logit" # "Logit;Delta;SS;IMD"
  MAX_DEPTH: [5]