DATASET: "DecMeg2014"
NUM_SPLITS: 3
WINDOW_LENGTH: 10
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "NONE"
NORMALIZATION: False
EXTRACTION: False
SELECTION:
  TYPE: "NONE"
  RATE: 0.1
EXPLAINER:
  TYPE: "Logit"