EXPERIMENT:
  NAME: ""
  TAG: "sdt, atcnet"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_sdt"
  B: "DecMeg2014_atcnet"
AUGMENTATION:
  TYPE: "BASE"
NORMALIZATION:
  FLAG: True
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.1
  Diff:
    WINDOW_LENGTH: 10
    M: 4
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 7
  MIN_SAMPLES_LEAF: 2