EXPERIMENT:
  NAME: ""
  TAG: "linear, atcnet"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_mlp"
  B: "DecMeg2014_varcnn"
AUGMENTATION:
  TYPE: "NONE"
NORMALIZATION:
  FLAG: False
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "NONE"
  RATE: 0.0625
  Diff:
    WINDOW_LENGTH: 50
    M: 2
EXPLAINER:
  TYPE: "Delta"
  MAX_DEPTH: 4
  MIN_SAMPLES_LEAF: 1