EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Aug,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 3
WINDOW_LENGTH: 10
MODEL_A: "hgrn"
MODEL_B: "varcnn"
AUGMENTATION: "BASE"
EXTRACTION: False
SELECTION:
  TYPE: "DiffShapley"
  RATE: 0.01
EXPLAINER:
  TYPE: "Logit"