EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 1  # 10 5 1
MODEL_A: "mlp"
MODEL_B: "hgrn"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 3.0
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6