EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Sel"
  CPU_COUNT: 4
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "sdt"
MODEL_B: "atcnet"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "Logit"