EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Aug"
DATASET: "DecMeg2014"
NUM_SPLITS: 3
WINDOW_LENGTH: 10
MODEL_A: "sdt_hgrn_fakd"
MODEL_B: "sdt"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Logit"