EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 2
MODEL_A: "sdt"
MODEL_B: "atcnet"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 4
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "SS"