EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 10
MODEL_A: "gnb"
MODEL_B: "rf"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "Logit"