EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Aug,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 5
MODEL_A: "sdt"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "Logit"