EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 10  # 10 5 1
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
AUGMENT_FACTOR: 2.0
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6