EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 25  # 25 10 5 1  10最好
MODEL_A: "hgrn"
MODEL_B: "atcnet"
AUGMENTATION: "Counterfactual"  # "Counterfactual"  "NONE"  "BASE"
AUGMENT_FACTOR: [3.0] # 1-5之间取3最好
Feature_SMOOTHING: False  # 平滑无优势
SELECTION:
  TYPE: "DiffShapley" # "DiffShapley" "NONE"
  Diff:
    M: 2  # 2 4 8中4最好
    THRESHOLD: [0.0]  # 3.0和6.0具有竞争力
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: [5]