EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 10
MODEL_A: "mlp"
MODEL_B: "varcnn"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "NONE"
EXPLAINER:
  TYPE: "Logit"