EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit,Aug,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 4
WINDOW_LENGTH: 10
MODEL_A: "sdt"
MODEL_B: "hgrn"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "Logit"