EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "Logit"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 10
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "BASE"
SELECTION:
  TYPE: "DiffShapley"
  Diff:
    M: 8
    THRESHOLD: 6.0
EXPLAINER:
  TYPE: "Logit"