EXPERIMENT:
  PROJECT: "DecMeg2014"
  TAG: "SS,Sel"
DATASET: "DecMeg2014"
NUM_SPLITS: 5
WINDOW_LENGTH: 10
MODEL_A: "rf"
MODEL_B: "atcnet"
AUGMENTATION: "NONE"
SELECTION:
  TYPE: "DiffShapley"
EXPLAINER:
  TYPE: "SS"