EXPERIMENT:
  NAME: ""
  TAG: "sdt_varcnn_fakd, sdt"
  PROJECT: "CamCAN_baselines"
DATASET:
  TYPE: "CamCAN"
  CHANNELS: 204
  POINTS: 100
  NUM_CLASSES: 2
MODELS:
  A: "CamCAN_sdt3_varcnn_fakd"
  B: "CamCAN_sdt3"
#GLOBAL:
#LOCAL:
