EXPERIMENT:
  NAME: ""
  TAG: "hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_hgrn"
  B: "DecMeg2014_sdt"
EXPLAINER:
  TYPE: "DeltaExplainer"
  MAX_DEPTH: 7