EXPERIMENT:
  NAME: ""
  TAG: "hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_hgrn"
  B: "DecMeg2014_sdt"
AUGMENTATION:
  TYPE: "NONE"
NORMALIZATION:
  FLAG: False
EXTRACTION:
  FLAG: False
SELECTION:
  TYPE: "LR"
  RATE: 0.01
  Diff:
    WINDOW_LENGTH: 250
    M: 4
EXPLAINER:
  TYPE: "Logit"
#  MAX_DEPTH: 5
#  MIN_SAMPLES_LEAF: 2