EXPERIMENT:
  NAME: ""
  TAG: "hgrn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_hgrn"
  B: "DecMeg2014_sdt"
AUGMENTATION:
  TYPE: "SMOTE"
SELECTION:
  TYPE: "Boruta"
  RATE: 0.01
EXPLAINER:
  TYPE: "Logit"
  MAX_DEPTH: 6
  MIN_SAMPLES_LEAF: 2