EXPERIMENT:
  NAME: ""
  TAG: "lfcnn,varcnn"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
  NUM_SPLITS: 3
MODELS:
  A: "DecMeg2014_lfcnn"
  B: "DecMeg2014_varcnn"
EXPLAINER:
  TYPE: "LogitDeltaRule"
  MAX_DEPTH: 5
  MIN_SAMPLES_LEAF: 4