EXPERIMENT:
  NAME: ""
  TAG: "lfcnn,sdt"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
MODELS:
  A: "DecMeg2014_lfcnn"
  B: "DecMeg2014_sdt"
#GLOBAL:
#LOCAL: