EXPERIMENT:
  NAME: ""
  TAG: "varcnn,hgrn"
  PROJECT: "DecMeg2014_baselines"
DATASET:
  TYPE: "DecMeg2014"
  CHANNELS: 204
  POINTS: 250
  NUM_CLASSES: 2
MODELS:
  A: "DecMeg2014_varcnn"
  B: "DecMeg2014_hgrn"
